-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         10.4.28-MariaDB - mariadb.org binary distribution
-- SO del servidor:              Win64
-- HeidiSQL Versión:             12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Volcando estructura de base de datos para anpacpivaldodubraes
DROP DATABASE IF EXISTS `anpacpivaldodubraes`;
CREATE DATABASE IF NOT EXISTS `anpacpivaldodubraes` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `anpacpivaldodubraes`;

-- Volcando estructura para tabla anpacpivaldodubraes.blog
DROP TABLE IF EXISTS `blog`;
CREATE TABLE IF NOT EXISTS `blog` (
  `Id_Entrada` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `Título` varchar(150) NOT NULL,
  `Descripción` longtext NOT NULL,
  `Imagen` varchar(150) DEFAULT NULL,
  `Fecha_Publicación` datetime NOT NULL,
  PRIMARY KEY (`Id_Entrada`)
) ENGINE=InnoDB AUTO_INCREMENT=56 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcando datos para la tabla anpacpivaldodubraes.blog: ~61 rows (aproximadamente)
REPLACE INTO `blog` (`Id_Entrada`, `Título`, `Descripción`, `Imagen`, `Fecha_Publicación`) VALUES
	(1, 'CHARLA-TALLER ONLINE', 'Este viernes a las 20.30 horas charla online. Enviamos hoy por correo electrónico a los socios/as un enlace para poder asistir. Recordad qué está prohibido grabar la charla por la Ley de Protección de Datos.', 'Imágenes/Blog/AprenderADicirNon.jpg', '2020-12-10 17:52:00'),
	(2, 'FELICES FIESTAS', 'Feliz Navidad. Disfrutemos de estas fiestas con responsabilidad y sentido, y más pronto que tarde saldremos de esta pandemia. Cuidaros.', 'Imágenes/Blog/BoNadal.jpg', '2020-12-22 18:14:00'),
	(3, 'CARNAVAL EN EL CPI BEMBIBRE: LOS MANDATOS DEL MECO', 'Este lunes toca llevar una bata.<br/><br/><img src="Imágenes/Blog/OsMandatosDoMecoRecortada.png" width="250" alt="Os mandatos do Meco"/><br/><br/><br/><a href="http://recunchodepistacho.blogspot.com/?m=1"><button>REFUGIO DE PISTACHO</button></a>', 'Imágenes/Blog/OsMandatosDoMeco.jpg', '2021-02-06 17:58:00'),
	(4, 'URGENTE: CUIDADORAS PARA O COMEDOR DEL CPI BEMBIBRE', 'Se necesitan tres cuidadoras para el comedor del CPI BEMBIBRE. Según las normas de la Consejería de Educación, <strong>LAS CUIDADORAS TENDRÍAN QUE SER PADRES/MADRES DE LOS/AS NIÑOS/AS DE ALUMNOS/AS DEL CENTRO O PERSONAS MAYORES DE 18 AÑOS CONVIVIENTES EN EL MISMO DOMICILIO</strong>. Si no se encuentran no se llegaría al ratio de niños/as del comedor por cuidador/a, con lo cual la Administración o bien disminuría el número de niños/as en el comedor (esto sería en función de kilometraje, necesidades, conciliación familiar, etc...) o bien se cerraría el comedor escolar. Rogamos la máxima difusión.', 'Imágenes/Blog/Cubiertos.png', '2021-02-10 15:45:00'),
	(5, 'INFORMACIÓN IMPORTANTE: MEJORAS EN EL CPI BEMBIBRE', 'Informamos que el pasado martes 9 de Febrero, mantuvimos una reunión con la dirección del Centro, con la finalidad de colaborar en la solicitud a la Consejería de Educación de una profunda reforma del Edificio de Educación Infantil y Primaria, que incluiría entre otras actuaciones la sustitución del tejado. El edificio data de mediados del año 1975 y presenta deficiencias muy importantes que se agravaron en los últimos años. Somos conscientes de la dificultad de conseguir esta mellora, sobre todo a corto plazo, ya que supone un gran coste económico que tiene que asumir la Consejería y con seguridad existen otros centros educativos con problemas y demandas similares, mas la ANPA y el Colegio, con la implicación del Ayuntamiento del Valle del Dubra, estamos dispuestos a realizar todas las xestións necesarias, para intentar lograr esa reforma que mejore las condiciones nas que desenvolven su actividad diaria los/as alumnos/as. En las fotografías que publicamos aparecen algunas de las deficiencias que presenta el edificio en la actualidad. Es importante recordar que la mayoría fueron arregladas en numerosas ocasiones, pero al poco tiempo todo vuelve a estar igual.', 'Imágenes/Blog/MellorasNoCPIBembibre.png', '2021-02-24 12:18:00'),
	(6, 'RELATORIO ONLINE "ESCUELA DE PADRES Y MADRES"', 'Desarrollar la asertividade. Viernes 5 de Marzo ás 20.30 horas. Impartido por la psicóloga Libertad Culebras.', 'Imágenes/Blog/DesenvolverAAsertividade.png', '2021-02-24 12:37:00'),
	(7, 'TEATRO', 'Este sábado 20 de Marzo a las 18 horas teatro para niños/as mayores de ocho años y adultos/as en el AUDITORIO de Bembibre, Valle del Dubra.', 'Imágenes/Blog/OsNenosDaVariola.png', '2021-03-18 11:27:00'),
	(8, 'MUY BUENAS NOTICIAS', 'La Xunta de Galicia aprueba un investimiento de 392.000 euros para arreglar las infraestructuras y equipamentos del CPI de Bembibre. De esto nos dimos cuenta hace unos meses en un reportaje fotográfico en la página del Facebook y en la página web del ANPA (<a href="https://www.anpacpibembibrevaldodubra.com">https://www.anpacpibembibrevaldodubra.com</a>). Desde el ANPA les damos las gracias a la Dirección del Centro y al Ayuntamientoo del Valle del Dubra por sus gestiones. Las obras comenzarán este verano y acabarán antes del comienzo del próximo curso.', 'Imágenes/Blog/Micrófono.png', '2021-05-13 17:50:00'),
	(9, 'ESPECTÁCULO DÍA DE LAS LETRAS GALLEGAS', 'Con motivo del Día de las Letras Gallegas 2021, este vienres 14 de Maio a las 20.00 horas tendremos en el auditorio un espectáculo dirigido a la mocedad que combina la narración oral co otras artes escénicas. Esta propuesta tienta hacer un breve recorrido por la obra de la poetisa Xela Arias, sumergiéndonos tanto en su poesía como en su obra narrativa.', 'Imágenes/Blog/DeTiEMailoMundoQueApañes.png', '2021-05-13 18:03:00'),
	(10, 'FP DUAL', 'FP DUAL: El próximo viernes 21 de Mayo, a las 20:00h en la Casa de la Cultura, charla de presentación de la FP Dual, una modalidad formativa en la que se compaginan los estudios en un centro educativo con la actividad en las empresas. Ventajas:<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Formación remunerada.<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Titulación oficial.<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Inserción laboral inmediata.<br/><br/>Anímate a venir e conocer esta vía formativa.<br/><br/>NOTA: Debido a que el aforo es limitado se aconseja inscribirse en el Ayuntamiento (981 88 90 00) para garantizar que todos/as puedan asistir.', 'Imágenes/Blog/FPDual.png', '2021-05-19 16:54:00'),
	(11, 'ESPECTÁCULO POÉTICO-MUSICAL Y HUMORÍSTICO', 'Entrada libre hasta completar aforo.', 'Imágenes/Blog/Aldaolado.png', '2021-05-23 19:04:00'),
	(12, 'MUY IMPORTANTE', 'Abierto el plazo para solicitar el fondo solidario de libros y ayudas para adquirir libros de texto, por parte de la Consejería de Educación.<br/><br/>Enlace: <a href="http://www.edu.xunta.gal/">http://www.edu.xunta.gal/</a>', 'Imágenes/Blog/FondoSolidarioDeLibrosEAxudas.png', '2021-05-31 20:24:00'),
	(13, 'SERVICIO DE MADRUGADORES CURSO 2021-2022.', 'Desde el ANPA en colaboración con el Ayuntamiento de Valle del Dubra estamos intentando ofertar el Servicio de Madrugadores, para eso necesitamos saber el número de niños/as que estuvieran interesados/as. Se necesita un número mínimo para que sea viable. Enviaremos un modelo de solicitud para cubrir los que esteáis interesados/as, y devolver cubierto al Buzón del ANPA antes del 11 de Junio.', 'Imágenes/Blog/ServicioDeMadrugadores.png', '2021-05-31 20:38:00'),
	(14, 'CONCILIA VERANO', 'Plazo de inscripción hasta el 21 de Junio. Precio: 4€/día.', 'Imágenes/Blog/ConciliaVerán.jpg', '2021-06-11 11:06:00'),
	(15, 'ASAMBLEA GENERAL ', 'Viernes 18 de Junio a las 21:00 horas en el gimnasio de secundaria del CPI de Bembibre. Orden del día: <br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Lectura y aprobación del Acta de la &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Asamblea anterior.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Estado de cuentas.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. Servicio de madrugadores.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4. Actividades extraescolares curso &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2021-2022 (grupos burbuja).<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5. Tareas realizadas por el ANPA en el &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;curso 2021-2022 (relatorios online, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reclamaciones del arreglo del colegio, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;etc..).<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6. Ruegos y preguntas.', 'Imágenes/Blog/Asamblea.jpg', '2021-06-11 11:11:00'),
	(16, 'MENÚ ESCOLAR JUNIO 2021', 'Estimadas familias,<br/><br/>Ya está puesto el menú del comedor para el mes de Junio.<br/><br/>Saludos cordiales.<br/><br/>El CPI de Bembibre.<br/><br/>URL: <a href="https://tokapp.com/url/8o2dy3io">https://tokapp.com/url/8o2dy3io</a>', 'Imágenes/Blog/MenúXuño2021.png', '2021-06-11 13:30:00'),
	(17, 'PATINAJE', 'Cómo bien sabéis, debido al protocolo COVID de la Consejería de Educación el ANPA no puede ofertar las actividades extraescolares (existencia de grupos burbuja en los centros educativos). Las actividades pueden hacerse siempre que sea a través de clubs federados. En el caso de patinaje se podría llevar a cabo, actividad que sería a cargo del Club Galia. Para esto los/as niños/as tendrían que federarse ya que es la única forma de poder hacer la actividad. La ficha federativa cuesta 20 euros y el precio de la clase depende del número de niños/as que se anoten. Sería Los sábados por la mañana y la profesora sería siendo Sheila. Para que el Club pueda montar los grupos necesitan saber quien quiere anotarse, para poder decirlo y que se pongan en contacto con ustedes. Enviad e-mail a <a href="mailto:bembibre.anpa@gmail.com">bembibre.anpa@gmail.com</a>.', 'Imágenes/Blog/Patinaxe.png', '2021-09-19 16:05:00'),
	(18, 'ASAMBLEA XERAL ', 'Viernes 24 de Septiembre a las 21:00 horas en el gimnasio de secundaria del CPI de Bembibre. Orden del día: <br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Lectura del Acta de la Asamblea &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;anterior.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Estado de cuentas de la Asociación.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. Cuota del ANPA y seguro escolar.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4. Hoja de inscripción de la ANPA y &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normativa de la protección de datos.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5. Actividades extraescolares y &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;protocolo COVID-19.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6. Ruegos e preguntas.', 'Imágenes/Blog/Asamblea.jpg', '2021-09-19 16:13:00'),
	(19, 'TALLERES DE TEATRO', 'Clases de Teatro en Santa Comba para todos/as, grupos para todas las edades.', 'Imágenes/Blog/TeatroMaiores.png', '2021-09-19 16:18:00'),
	(20, 'TALLERES DE TEATRO', 'Clases de Teatro en Santa Comba para niños/as.', 'Imágenes/Blog/TeatroNenos.png', '2021-09-19 16:23:00'),
	(21, 'PORNOGRAFÍA Y CAMBIOS EN LAS RELACIONES INTERPERSONALES', 'CHARLAS PADRES E MADRES: "Pornografía y cambios en las relaciones interpersonales". Lunes 15 de Noviembre y lunes 22 de Noviembre desde las 18:00 hasta las 19:30 horas en el Auditorio del Ayuntamiento de Bembibre. Internet es hoy la fuente principal de educación sexual de la juventud: el acceso a la pornografía machista y vejatoria se generaliza a partir de los 14 años. ¿CÓMO DEBEMOS EDUCAR PARA FOMENTAR RELACIONES SEXUALES Y AFECTIVAS LIBRES, IGUALITARIAS Y RESPETUOSAS CON LA DIVERSIDAD?', 'Imágenes/Blog/PornografíaECambiosNasRelaciónsInterpersoais.png', '2021-11-11 21:25:00'),
	(22, 'CRECIENDO CON INTERNET Y LAS REDES SOCIALES: CLAVES PARA COMPENDER E PREVENIR', 'IMPORTANTE: Martes 25 de Enero a las 19.30 horas en el Auditorio de Bembibre, charla: "Crecienndo con Internet y las redes sociais: claves para comprender e prevenir". Impartida por la psicóloga Patricia Gómez Salgado (Investigadora de la USC. Experta en adolescentes y TICs). Esta charla se realiza con la ayuda del Centro Autonómico de Formación e Innovación (CAFI) de la Consejería de Cultura, Educación y Universidad.', 'Imágenes/Blog/RiscosDoUsoDeInternetEAsRedesSociais.png', '2022-01-20 22:32:00'),
	(23, 'AYUDAS PARA LIBROS Y MATERIAL ESCOLAR', 'La Xunta abre el plazo para que las familias soliciten yxudas para libros y material escolar y acceso al fondo solidario de manuais.<br/><br/>Más información en la páxina web: <a href="https://www.xunta.gal/notas-de-prensa/-/nova/69002/xunta-abre-prazo-para-que-familias-soliciten-axudas-para-libros-material-escolar">https://www.xunta.gal/notas-de-prensa/-/nova/69002/xunta-abre-prazo-para-que-familias-soliciten-axudas-para-libros-material-escolar</a>.', 'Imágenes/Blog/LibrosEMaterialEscolar.png', '2022-05-23 17:25:00'),
	(24, 'COMIENZO DEL CURSO ESCOLAR 2022/2023', 'El próximo jueves día 8 comienza el curso escolar 2022-23 y desde el ANPA CPI Bembibre deseamos un muy buen curso para niños/as, profes, profesores/as, nais/pais y todo el personal del CPI Bembibre.<br/><br/>Páina web del calendario escolar: <a href="https://www.eldiario.es/galicia/calendario-escolar-curso-2022-23-galicia-inicio-clases-vacaciones-dias-no-lectivos_1_9046076.html">https://www.eldiario.es/galicia/calendario-escolar-curso-2022-23-galicia-inicio-clases-vacaciones-dias-no-lectivos_1_9046076.html</a>', 'Imágenes/Blog/CalendarioEscolar22-23.png', '2022-09-04 19:32:00'),
	(25, 'MENÚ ESCOLAR SEPTIEMBRE 2022', 'Menú del comedor escolar para el mes de Septiembre.', 'Imágenes/Blog/MenúSetembro2022.png', '2022-09-10 12:53:00'),
	(26, 'BONO CUIDADO, UNA AYUDA PARA LA CONCILIACIÓN FAMILIAR', 'Más información:<br/><br/><a href="https://politicasocial.xunta.gal/es/recursos/ayudas/bono-coidado-una-ayuda-para-la-conciliacion-de-las-familias">https://politicasocial.xunta.gal/es/recursos/ayudas/bono-coidado-una-ayuda-para-la-conciliacion-de-las-familias</a>', 'Imágenes/Blog/BonoCoidadoXunta.png', '2022-09-10 13:01:00'),
	(27, 'I EDICIÓN SANTIAGO DE COMPOSTELA EN MARCHA CONTRA EL CÁNCER', 'Caminata solidaria (5km) y Feria divulgativa "Ciencia para todos".<br/><br/>Más información:<br/<br/><a href="https://enmarchacontraelcancer.es/es/evento/santiago-de-compostela-en-marcha-contra-o-cancro">https://enmarchacontraelcancer.es/es/evento/santiago-de-compostela-en-marcha-contra-o-cancro</a>.', 'Imágenes/Blog/IEdiciónMarchaContraOCancro.jpg', '2022-09-16 22:20:00'),
	(28, 'AVISO IMPORTANTE', 'Este viernes 30 de septiembre acaba el plazo para hacerse socio/a del ANPA. Recordad enviar solicitud de inscripción y hacer el ingreso. Cuota: 15€ por familia.', 'Imágenes/logo.png', '2022-09-29 19:50:00'),
	(29, 'CURSOS DE FORMACIÓN PARA MUJERES', 'Cursos gratuitos de formación en competencias digitales para mujeres desempleadas o en demanda de la mejora de empleo. A finales de curso llevan una TABLET de Regalo. Más información en <a href="https://www.mullerdixital.gal/">www.mullerdixital.gal</a>.', 'Imágenes/Blog/MullerDixital.png', '2022-12-19 20:54:00'),
	(30, 'CAMPAÑA SOLIDARIA DE RECOGIDA DE ALIMENTOS', 'Desde Cáritas Val do Dubra nos piden la colaboración en la recogida de alimentos no percederos. En el Colegio CPI de Bembibre va haber un espacio habilitado en el hall de la entrada para depositar alimentos no percederos y aquellas familias que quieran colaborar pueden allegar los alimentos a través de sus hijos/as. Desde el ANPA CPI Bembibre solicitamos la colaboración de todos/as en esta campaña solidaria.', 'Imágenes/Blog/Cáritas.png', '2022-12-19 21:00:00'),
	(31, 'COLABORADORAS/ES PARA EL COMEDOR ESCOLAR DEL CPI BEMBIBRE', 'URGENTE: Se necesitan colaboradoras/es para el comedor escolar del CPI Bembibre (Val do Dubra - A Coruña). El número de colaboradoras/es va en función del número de niños/as que comen en el comedor escolar, si hay menos colaboradoras/es habrá menos niños/as en el comedor escolar. Para evitar esto necesitamos colaboradores/as para el comedor escolar del CPI Bembibre. Pueden ser colaboradoras/es del comedor escolar: padres y madres, familiares de alumnos/as (tios, abuelos, y hermanos mayores de edad), ex-colaboradores de este servicio, personas que participen en programas de voluntariado social en ayuntamientos o en ONGS. Los colaboradores/as pueden comer de forma gratuita en el centro los días que colaboren y perciban 12,50 euros por asistencia. El horario es desde las 14:15 horas (pueden comer antes) hasta las 16:15 horas. Si hay personas interesadas que se pongan en contacto con el centro lo antes posible.', 'Imágenes/Blog/ColexioDeBembibre.jpg', '2023-03-29 12:14:58'),
	(32, 'CAMPAMENTOS DE VERANO 2023', 'Ábrese el plazo hasta el 2 de Mayo para solicitar plaza para los campamentos que oferta la Xunta de Galicia para niños de 9 a 17 años. Las solicitudes se tramitarán a través de la sede electrónica de la Xunta.', 'Imágenes/Blog/Campamentos2023.jpg', '2023-04-20 19:18:37'),
	(33, 'TEATRO PARA TODOS/AS', 'Este sábado 29 de Abril a las 18:00 da tarde Teatro para niños/as y padres y madres en el Auditorio de Bembibre (Valle del Dubra).', 'Imágenes/Blog/TeatroAsPalabrasPerdidas.jpg', '2023-04-26 11:29:43'),
	(34, 'ASAMBLEA GENERAL', 'Orden del día de la Asamblea General de Socios/as el 9 de Junio en el Gimnasio Secundaria del CPI Bembibre a las 21.30 horas:<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Lectura y aprobación da acta da Asamblea Anterior.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Estado de contas.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. Dimisión de algunos/as integrantes de la Directiva y nuevas incorporaciones a la Directiva.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4. Votación para decidir si se hace o no la Fiesta de Fin de Curso.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5. Votación para decidir si se hace la aportación del ANPA a la Excursión de Fin de Curso, y en el caso de hacerla si se hace para los socios/as del ANPA o para todo/as (socios/as o no socios/as)<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6. Ruegos e preguntas', 'Imágenes/Blog/ColexioDeBembibre.jpg', '2023-05-30 22:27:19'),
	(35, 'FIESTA ANPA FIN DE CURSO', 'El próximo domingo 25 de Junio tendrá lugar la Fiesta de Fin de Curso en el patio del CPI Bembibre, a partir de las 16.30 horas.\r\nHabrá hinchables y Fiesta de la Espuma y meriendas para todos/as\r\nEnviar un correo al e-mail de la ANPA (bembibre.anpa@gmail.com) diciendo cuantos niños/as y adultos/as vienen a la Fiesta ANTES del martes 20 de Junio.\r\nTodos los niños/as tienen que estar acompañados por un adulto/a.\r\nImportante: notificar en el correo si hay algún niño/a con intolerancia alimentaria y de que tipo.\r\nLa Fiesta es GRATIS para los socios/as.\r\nLos no socios/as pueden asistir pagando 15 euros por familia.', 'Imágenes/Blog/ColexioDeBembibre.jpg', '2023-06-14 11:28:38'),
	(36, 'FIESTA ANPA CPI BEMBIBRE', 'Fiesta del ANPA del CPI Bembibre del 25 de Junio.', 'Imágenes/Blog/FestaANPACpiBembibre.jpg', '2023-09-25 11:23:41'),
	(37, 'ASAMBLEA GENERAL', 'ASAMBLEA GENERAL SOCIOS/AS Viernes 15 de Septiembre a las 21 horas en el Gimnasio de Secundaria CPI Bembibre. Orden del día de la Asamblea: \r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Lectura y aprobación del Acta de la Asamblea Anterior.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Estado de cuentas de la Asociación.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. Dimisión de la Junta Directiva y elección de la nueva Junta Directiva.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4. Actividades Extraescolares.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5. Uniforme escolar alumnado CPI Bembibre.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6. Ruegos y Preguntas.', 'Imágenes/Blog/ColexioDeBembibre.jpg', '2023-09-09 11:58:33'),
	(38, 'ACTIVIDADES EXTRAESCOLARES Y CUOTA DEL SOCIO/A ', 'CURSO 2023/2024 \r\nACTIVIDADES EXTRAESCOLARES ANPA CPI BEMBIBRE Y CUOTA DE SOCIO/A.\r\nEl próximo día 27 de Septiembre es el último día para anotarse en las actividades extraescolares del ANPA. \r\nEste año ofrecemos:\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Pintura: 22 euros/mes.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Danza: 21 euros/mes.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Mecanografia: 22 euros/mes.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Robótica: 22 euros/mes.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Inglés: 22 euros/mes.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Teatro: 27 euros /mes.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Multideporte: 24 euros/mes.<br/><br/>\r\nComo dijimos en la Asamblea este curso sólo tenemos un aula para las clases de inglés y pintura con lo cual los grupos de niños/as van a ser distintos al año pasado, para poder tener estas dos actividades extraescolares.\r\nLos primeros 15 días de Octubre habá jornadas de Puertas Abiertas, para que los niños/as vean si les gusta la actividad.\r\nUna vez anotado definitivamente un niño/a no podrá dejar la actividad, excepto causa de fuerza mayor.\r\nPara poder ir a las actividades hay que ser socio/a de la ANPA.\r\nLa cuota de socio es por curso, son 15 euros *por familia*.\r\nHay que ingresar los 15 euros en la cuenta bancaria del ANPA antes del 31 de Octubre.\r\nEl seguro escolar del ANPA son 10 euros *por niño/a* por curso.\r\nRecordamos que este seguro es voluntario.\r\nCorreo electrónico ANPA CPI Bembibre: <a href="mailto:bembibre.anpa@gmail.com">bembibre.anpa@gmail.com</a>', 'Imágenes/Blog/ColexioDeBembibre.jpg', '2023-09-18 21:07:23'),
	(39, 'ACTIVIDAD EXTRAESCOLAR DE TEATRO', 'ACTIVIDAD EXTRAESCOLAR ANPA CPI BEMBIBRE. A partir de siete años de edad.', 'Imágenes/Blog/TeatroActividadeExtraescolarCurso2324.jpg', '2023-10-04 16:23:28'),
	(40, 'TEATRO FAMILIAR', 'TEATRO FAMILIAR este sábado 18 de Novembro a las 20 horas en el Auditorio Municipal en Bembibre (Valle del Dubra).', 'Imágenes/Blog/TeatroFamiliar.jpg', '2023-11-16 19:39:20'),
	(41, 'CAMPAMENTO DE NAVIDAD EN VALLE DEL DUBRA', 'Campamento de navidad en el Valle Del Dubra.', 'Imágenes/Blog/CampamentoNadal.jpg', '2023-11-23 17:01:56'),
	(42, 'CAMPAMENTO DE NAVIDAD DE MULTIDEPORTE', 'CAMPAMENTO DE NAVIDAD DE MULTIDEPORTE DEL ANPA DE BEMBIBRE\r\nDesde hoy y hasta el 3 de Diciembre se encuentra abierta la inscripción del Campamento de Navidad del ANPA del CPI de Bembibre\r\nSemana 1: Del 26 al 29 de Diciembre.\r\nSemana 2: Del 2 al 5 de Enero.\r\nHorario: 09:00-14:00\r\n(Posibilidad de elegir semanas sueltas). \r\n65€ a la semana\r\n15€ día suelto\r\n95€ campus completo\r\nSe hará un descuento de 15€ a los niños/as que ya están asistiendo a multideporte (del ANPA).\r\nSe necesita un mínimo de 10 asistentes.\r\nINFÓRMATE LLAMANDO AL 616 25 40 95.\r\n<br/>\r\nEnlace: <a href="https://docs.google.com/forms/d/e/1FAIpQLScmnX8euSrYJ9CVnhLxjrgdLzYJieBcySxnT5CmNd1TpYBLOw/viewform">Formulario KFSport</a>', 'Imágenes/Blog/KFSport.png', '2023-11-23 17:04:49'),
	(43, 'CAMPAMENTO ANPA MULTIDEPORTE NAVIDAD 2023', 'CAMPAMENTO ANPA MULTIDEPORTE NAVIDAD 2023.', 'Imágenes/Blog/CampusDeportivo.jpg', '2023-11-23 17:07:45'),
	(45, 'CAMPAMENTO DE CARNAVAL VALLE DEL DUBRA', 'Inscrición gratuita.', 'Imágenes/Blog/CampamentoDeEntroido.jpg', '2023-12-08 18:47:04'),
	(46, '1º PREMIO DEL CLUB DEBATE ALINGUA', 'ENHORABUENA A LOS TESTUDOS (CPI de Bembibre). Muchas felicidades y mucha suerte en la Final.', 'Imágenes/Blog/PremioClubDebateAlingua.jpg', '2024-01-20 17:09:24'),
	(47, 'TESTUDOS DE BEMBIBRE', 'ENHORABUENA A LOS AOS TESTUDOS DE BEMBIBRE (CPI de Bembibre). Los chicos y chicas de Valle del Dubra consiguen su plaza para la final del @clubdedebate_alingua \r\nLos 𝐓𝐞𝐬𝐭𝐮𝐝𝐨𝐬 𝐝𝐞 𝐁𝐞𝐦𝐛𝐢𝐛𝐫𝐞, representando al Ayuntamiento de Valle del Dubra, ganan el primer premio de 800 euros y pasan a la final.\r\nA final da actividade terá lugar el 13 de Abril y acogida por el Ayuntamiento de Valle Del Dubra', 'Imágenes/Blog/TestudosDeBembibre.jpg', '2024-03-01 19:54:33'),
	(48, 'RELATORIO "CUIDANDO LA SALUD MENTAL DE NUESTROS HIJOS/AS"', 'RELATORIO "CUIDANDO LA SALUD MENTAL DE NUESTROS HIJOS/AS" LUNES 22 de Abril a las 20 horas en la Casa de la Cultura de Bembibre. Impartido por la psicóloga Belén Montesa Lou. Nos hablará de la importancia de la autoestima y la regulación de las emociones y como identificar las señales de alerta de posibles problemas emocionales. También se abordarán métodos efectivos para \r\npromover un ambente familiar positivo y de apoyo que contribuya el bienestar emocional y mental de los niños/as. Relatorio financiado por el CAFI, Consejería de Educación.', 'Imágenes/Blog/RelatorioCoidandoASaúdeMentalDosNososFillos.jpg', '2024-03-01 20:18:12'),
	(49, 'TORNEO ESCOLAR AJEDREZ XOGADE', 'TORNEO ESCOLAR AJEDREZ XOGADE. Este jueves 28 de Marzo en la Casa da Cultura de Bembibre, de 12.30 a 14 horas.<br/><br/>Edad: hasta Segundo de la ESO.', 'Imágenes/Blog/TorneoEscolarXadrezXogade.jpg', '2024-03-26 17:04:38'),
	(50, 'CÓMO PREVENIR EL CONSUMO DE SUSTANCIAS ADICTIVAS DESDE LA FAMILIA', 'LUNES 8 ABRIL a las 20 horas, Casa de la Cultura de Bembibre, " CÓMO PREVENIR EL CONSUMO DE SUSTANCIAS ADICTIVAS DESDE LA FAMILIA". Hablará Miriam Otero, Dra. en Psicología. Relatorio financiado por el CAFI, Consejería de Educación.', 'Imágenes/Blog/ComoPrevirOConsumoDeSustanciaAditivasDendeAFamilia.jpg', '2024-04-03 17:30:24'),
	(51, 'DÍA DEL LIBRO. PACO NOGUEIRAS CUENTOS A CIENTOS', 'ESTE VIERNES A LAS 19 HORAS EN LA BIBLIOTECA DE LA CASA DE LA CULTURA', 'Imágenes/Blog/PacoNogueirasContosACentos.jpg', '2024-04-03 17:36:29'),
	(52, 'FINAL CLUB DEBATE ALINGUA', 'HOY "Los Testudos del CPI Bembibre" disputan la Final del Club Debate A Lingua a partir de las 10.30 en el Auditorio de Valle del Dubra. Desde la ANPA les deseamos suerte y expresamos nuestra admiración por su gran trabajo.', 'Imágenes/Blog/ClubDebateALingua.jpg', '2024-04-13 09:04:20'),
	(53, 'FESTIVAL ACTIVIDADES EXTRAESCOLARES', 'SÁBADO 4 DE MAYO: FESTIVAL ACTIVIDADES EXTRAESCOLARES.', 'Imágenes/Blog/FestivalActividadesExtraescolares.jpg', '2024-04-18 18:02:36'),
	(54, 'DETALLES FESTIVAL ACTIVIDADES EXTRAESCOLARES', 'Sábado 4  de mayo FESTIVAL ACTIVIDADES EXTRAESCOLARES ANPA CPI BEMBIBRE. La ANPA traerá pizza y bebida para los niños/as.', 'Imágenes/Blog/FestivalANPABembibre.jpg', '2024-05-01 11:07:22'),
	(55, 'FINAL DE LA OLIMPIADA GALLEGA DE MATEMÁTICAS', 'EL CPI BEMBIBRE PASA A LA FASE FINAL DE LA OLIMPIADA GALLEGA DE MATEMÁTICAS. La fase final se disputará en Lugo el 23 de Mayo. Muchas felicidades a Nicolás Amado, representante del CPI Bembibre en la Olimpiada Matemática. Nicolás es Subcampión Gallego de Ajedrez Sub-14, jugador del Club Ajedrez Valle del Dubra. Ajedrez y matemáticas un binomio perfecto. Más info en <a href="https://agapema.org/.../centros-inscritos-para-a.../">https://agapema.org/.../centros-inscritos-para-a.../</a>', 'Imágenes/Blog/FinalDaOlimpiadaGalegaDeMatemáticas.jpg', '2024-05-09 16:11:30'),
	(56, 'ASAMBLEA GENERAL', 'ASAMBLEA GENERAL SOCIOS/AS VIERNES 7 JUNIO A LAS 21.30 HORAS en la Biblioteca de Secundaria.\r\nOrden del día:<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n1. Lectura del acta de la Asamblea anterior.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n2. Estado de cuentas de la asociación.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n3. Dimisión y elección de integrantes de la Directiva.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n4. Excursión ANPA 30 de Junio.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n5. Actividades extraescolares.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n6. Ruegos y preguntas.', 'Imágenes/Blog/ColexioDeBembibre.jpg', '2024-05-30 12:08:04'),
	(57, 'JORNADA ACTIVIDAD EXTRAESCOLAR MULTIDEPORTE EN SANTA COMBA', 'Viernes 14 Junio Xornada Actividad Extraescolar Multideporte en Santa Comba.\r\nAnimaros a participar. INSCRIPCIÓN antes del miércoles 5 de Junio. Enviar nombre y apellidos do niño/a y fecha de nacimiento a Kevin (616254095).', 'Imágenes/Blog/XornadaMultideporteSantaComba.jpg', '2024-05-30 19:21:47'),
	(58, 'EXCURSIÓN ANPA ECO-PARQUE ATALAYA ', 'Domingo 30 de Junio. Salida a las 09:00 horas desde el CPI de Bembibre. La excursión incluye las actividades en el Eco-parque, la comida completa del medio-día y el viaje en autobús. Los niños/as de los socios/as del ANPA no pagan nada. Prezo adulto socio/a 37 euros. Los niños/as NO socios/as precio 30 euros y el adulto no socio 47 euros. Importante: úlimo día para anotarse el 13 de Junio.', 'Imágenes/Blog/ExcursiónEcoParqueAtalaia.jpg', '2024-05-31 20:45:15'),
	(59, 'PLAZAS AGOTADAS PARA LA EXCURSIÓN AL ECO-PARQUE ATALAYA', 'EXCURSIÓN ANPA 30 DE XUÑO ECO-PARQUE ATALAYA. Después de acabar el prazo de inscripción, y debido a que ya no hay plazas, NO se anota a más participantes. Feliciadades a todos/as por el éxito de la convocatoria.', 'Imágenes/Blog/EcoParqueAtalaia.jpg', '2024-06-15 18:33:16'),
	(60, 'ECO-PARQUE ATALAYA (COTOBADE)', 'EXCURSION ANPA CPI BEMBIBRE ECO-PARQUE ATALAYA (Cotobade)', 'Imágenes/Blog/ExcursionistascoParqueAtalaia.jpg', '2024-07-01 12:47:12'),
	(61, 'CAMPAMENTO DIGITAL EN VALLE DEL DUBRA', 'Abierta la preinscripción para el #CampamentoDixital en Valle del Dubra.<br/><br/>\r\nSi tienes entre 9 e 17 años, ¡participa en este campamento gratuíto de 30 horas para aprender competencias digitales!<br/><br/>\r\nDel 7 de Octubre al 29 de Noviembre, en las tardes de los lunes y jueves en la Biblioteca Municipal de Valle del Dubra.<br/><br/>\r\nDos grupos disponibles:<br/><br/>\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- 9 a 13 años: 17:00 - 19:00 h.\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- 14 a 17 años: 19:00 - 21:00 h.<br/><br/>\r\nAprende sobre seguridad en la red, uso responsable de las redes sociales y mucho más, todo mientras te diviertes en aventuras digitales adaptadas a tu edad.<br/><br/>\r\nInscripción abierta hasta el 25 de Septiembre en el Registro General del Ayuntamiento o a través de la sede electrónica.<br/><br/>\r\n¡No pierdas la oportunidad!', 'Imágenes/Blog/CampamentoDixital.jpg', '2024-09-12 17:58:47'),
	(62, 'ASAMBLEA GENERAL', 'CONVOCATORIA ASAMBLEA XERAL SOCIOS/AS ANPA CPI BEMBIBRE:<br/><br/>\r\nViernes 13 de Septiembre a las 21.30 horas en la Biblioteca de Secundaria del CPI Bembibre.<br/><br/>\r\nOrden del día:<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n1. Lectura y aprobación del acta de la Asamblea General Anterior.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n2. Estado de cuentas de la Asociación.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n3. Renovación de integrantes de la directiva ANPA.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n4. Actividades extraescolares curso 2024/2025.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n5. Ruegos y preguntas.', 'Imágenes/Blog/ColexioDeBembibre.jpg', '2024-09-25 21:52:20');

-- Volcando estructura para tabla anpacpivaldodubraes.comentarios
DROP TABLE IF EXISTS `comentarios`;
CREATE TABLE IF NOT EXISTS `comentarios` (
  `Id_Comentario` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `Nombre` varchar(100) NOT NULL,
  `Correo` varchar(100) NOT NULL,
  `Comentario` longtext NOT NULL,
  `Fecha_Publicación` datetime NOT NULL,
  PRIMARY KEY (`Id_Comentario`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcando datos para la tabla anpacpivaldodubraes.comentarios: ~1 rows (aproximadamente)
REPLACE INTO `comentarios` (`Id_Comentario`, `Nombre`, `Correo`, `Comentario`, `Fecha_Publicación`) VALUES
	(1, 'Blasco Rodríguez Porta', 'blascorodriguez@gmail.com', 'Comentario de prueba desde la página de contacto.', '2024-09-21 22:42:15');

-- Volcando estructura para tabla anpacpivaldodubraes.usuarios
DROP TABLE IF EXISTS `usuarios`;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `Id_Usuario` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `Usuario` varchar(50) NOT NULL,
  `Contraseña` varchar(50) NOT NULL,
  `Nombre` varchar(100) NOT NULL,
  `Correo` varchar(100) NOT NULL,
  `Teléfono` varchar(20) DEFAULT NULL,
  `Encuentro` enum('Motor de búsqueda','Medios sociales','TV','Radio','Amigo o familiar') DEFAULT NULL,
  `OtrosDetalles` longtext DEFAULT NULL,
  `MeGustaIndex` enum('Sí','No') NOT NULL,
  `MeGustaSobreNosotros` enum('Sí','No') NOT NULL,
  `MeGustaEstatutos` enum('Sí','No') NOT NULL,
  `MeGustaContacto` enum('Sí','No') NOT NULL,
  PRIMARY KEY (`Id_Usuario`),
  UNIQUE KEY `Usuario` (`Usuario`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcando datos para la tabla anpacpivaldodubraes.usuarios: ~2 rows (aproximadamente)
REPLACE INTO `usuarios` (`Id_Usuario`, `Usuario`, `Contraseña`, `Nombre`, `Correo`, `Teléfono`, `Encuentro`, `OtrosDetalles`, `MeGustaIndex`, `MeGustaSobreNosotros`, `MeGustaEstatutos`, `MeGustaContacto`) VALUES
	(1, 'admin', 'abc123.,', 'Administrador', 'admin@admin.es', '608736780', 'Amigo o familiar', NULL, 'No', 'No', 'No', 'No'),
	(2, 'juaninsua', 'abc123.,', 'Juan José Insua Louro', 'juan.insua.bembibre@edu.xunta.es', '678491234', 'Medios sociales', 'Hola Blasco, soy Juan el compañero de Ruth.', 'No', 'No', 'No', 'No');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;

-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         10.4.28-MariaDB - mariadb.org binary distribution
-- SO del servidor:              Win64
-- HeidiSQL Versión:             12.6.0.6765
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Volcando estructura de base de datos para anpacpivaldodubraes
DROP DATABASE IF EXISTS `anpacpivaldodubraes`;
CREATE DATABASE IF NOT EXISTS `anpacpivaldodubraes` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `anpacpivaldodubraes`;

-- Volcando estructura para tabla anpacpivaldodubraes.blog
DROP TABLE IF EXISTS `blog`;
CREATE TABLE IF NOT EXISTS `blog` (
  `Id_Entrada` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `Título` varchar(150) NOT NULL,
  `Descripción` longtext NOT NULL,
  `Imagen` varchar(150) DEFAULT NULL,
  `Fecha_Publicación` datetime NOT NULL,
  PRIMARY KEY (`Id_Entrada`)
) ENGINE=InnoDB AUTO_INCREMENT=56 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcando datos para la tabla anpacpivaldodubraes.blog: ~61 rows (aproximadamente)
REPLACE INTO `blog` (`Id_Entrada`, `Título`, `Descripción`, `Imagen`, `Fecha_Publicación`) VALUES
	(1, 'CHARLA-TALLER ONLINE', 'Este viernes a las 20.30 horas charla online. Enviamos hoy por correo electrónico a los socios/as un enlace para poder asistir. Recordad qué está prohibido grabar la charla por la Ley de Protección de Datos.', 'Imágenes/Blog/AprenderADicirNon.jpg', '2020-12-10 17:52:00'),
	(2, 'FELICES FIESTAS', 'Feliz Navidad. Disfrutemos de estas fiestas con responsabilidad y sentido, y más pronto que tarde saldremos de esta pandemia. Cuidaros.', 'Imágenes/Blog/BoNadal.jpg', '2020-12-22 18:14:00'),
	(3, 'CARNAVAL EN EL CPI BEMBIBRE: LOS MANDATOS DEL MECO', 'Este lunes toca llevar una bata.<br/><br/><img src="Imágenes/Blog/OsMandatosDoMecoRecortada.png" width="250" alt="Os mandatos do Meco"/><br/><br/><br/><a href="http://recunchodepistacho.blogspot.com/?m=1"><button>REFUGIO DE PISTACHO</button></a>', 'Imágenes/Blog/OsMandatosDoMeco.jpg', '2021-02-06 17:58:00'),
	(4, 'URGENTE: CUIDADORAS PARA O COMEDOR DEL CPI BEMBIBRE', 'Se necesitan tres cuidadoras para el comedor del CPI BEMBIBRE. Según las normas de la Consejería de Educación, <strong>LAS CUIDADORAS TENDRÍAN QUE SER PADRES/MADRES DE LOS/AS NIÑOS/AS DE ALUMNOS/AS DEL CENTRO O PERSONAS MAYORES DE 18 AÑOS CONVIVIENTES EN EL MISMO DOMICILIO</strong>. Si no se encuentran no se llegaría al ratio de niños/as del comedor por cuidador/a, con lo cual la Administración o bien disminuría el número de niños/as en el comedor (esto sería en función de kilometraje, necesidades, conciliación familiar, etc...) o bien se cerraría el comedor escolar. Rogamos la máxima difusión.', 'Imágenes/Blog/Cubiertos.png', '2021-02-10 15:45:00'),
	(5, 'INFORMACIÓN IMPORTANTE: MEJORAS EN EL CPI BEMBIBRE', 'Informamos que el pasado martes 9 de Febrero, mantuvimos una reunión con la dirección del Centro, con la finalidad de colaborar en la solicitud a la Consejería de Educación de una profunda reforma del Edificio de Educación Infantil y Primaria, que incluiría entre otras actuaciones la sustitución del tejado. El edificio data de mediados del año 1975 y presenta deficiencias muy importantes que se agravaron en los últimos años. Somos conscientes de la dificultad de conseguir esta mellora, sobre todo a corto plazo, ya que supone un gran coste económico que tiene que asumir la Consejería y con seguridad existen otros centros educativos con problemas y demandas similares, mas la ANPA y el Colegio, con la implicación del Ayuntamiento del Valle del Dubra, estamos dispuestos a realizar todas las xestións necesarias, para intentar lograr esa reforma que mejore las condiciones nas que desenvolven su actividad diaria los/as alumnos/as. En las fotografías que publicamos aparecen algunas de las deficiencias que presenta el edificio en la actualidad. Es importante recordar que la mayoría fueron arregladas en numerosas ocasiones, pero al poco tiempo todo vuelve a estar igual.', 'Imágenes/Blog/MellorasNoCPIBembibre.png', '2021-02-24 12:18:00'),
	(6, 'RELATORIO ONLINE "ESCUELA DE PADRES Y MADRES"', 'Desarrollar la asertividade. Viernes 5 de Marzo ás 20.30 horas. Impartido por la psicóloga Libertad Culebras.', 'Imágenes/Blog/DesenvolverAAsertividade.png', '2021-02-24 12:37:00'),
	(7, 'TEATRO', 'Este sábado 20 de Marzo a las 18 horas teatro para niños/as mayores de ocho años y adultos/as en el AUDITORIO de Bembibre, Valle del Dubra.', 'Imágenes/Blog/OsNenosDaVariola.png', '2021-03-18 11:27:00'),
	(8, 'MUY BUENAS NOTICIAS', 'La Xunta de Galicia aprueba un investimiento de 392.000 euros para arreglar las infraestructuras y equipamentos del CPI de Bembibre. De esto nos dimos cuenta hace unos meses en un reportaje fotográfico en la página del Facebook y en la página web del ANPA (<a href="https://www.anpacpibembibrevaldodubra.com">https://www.anpacpibembibrevaldodubra.com</a>). Desde el ANPA les damos las gracias a la Dirección del Centro y al Ayuntamientoo del Valle del Dubra por sus gestiones. Las obras comenzarán este verano y acabarán antes del comienzo del próximo curso.', 'Imágenes/Blog/Micrófono.png', '2021-05-13 17:50:00'),
	(9, 'ESPECTÁCULO DÍA DE LAS LETRAS GALLEGAS', 'Con motivo del Día de las Letras Gallegas 2021, este vienres 14 de Maio a las 20.00 horas tendremos en el auditorio un espectáculo dirigido a la mocedad que combina la narración oral co otras artes escénicas. Esta propuesta tienta hacer un breve recorrido por la obra de la poetisa Xela Arias, sumergiéndonos tanto en su poesía como en su obra narrativa.', 'Imágenes/Blog/DeTiEMailoMundoQueApañes.png', '2021-05-13 18:03:00'),
	(10, 'FP DUAL', 'FP DUAL: El próximo viernes 21 de Mayo, a las 20:00h en la Casa de la Cultura, charla de presentación de la FP Dual, una modalidad formativa en la que se compaginan los estudios en un centro educativo con la actividad en las empresas. Ventajas:<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Formación remunerada.<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Titulación oficial.<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Inserción laboral inmediata.<br/><br/>Anímate a venir e conocer esta vía formativa.<br/><br/>NOTA: Debido a que el aforo es limitado se aconseja inscribirse en el Ayuntamiento (981 88 90 00) para garantizar que todos/as puedan asistir.', 'Imágenes/Blog/FPDual.png', '2021-05-19 16:54:00'),
	(11, 'ESPECTÁCULO POÉTICO-MUSICAL Y HUMORÍSTICO', 'Entrada libre hasta completar aforo.', 'Imágenes/Blog/Aldaolado.png', '2021-05-23 19:04:00'),
	(12, 'MUY IMPORTANTE', 'Abierto el plazo para solicitar el fondo solidario de libros y ayudas para adquirir libros de texto, por parte de la Consejería de Educación.<br/><br/>Enlace: <a href="http://www.edu.xunta.gal/">http://www.edu.xunta.gal/</a>', 'Imágenes/Blog/FondoSolidarioDeLibrosEAxudas.png', '2021-05-31 20:24:00'),
	(13, 'SERVICIO DE MADRUGADORES CURSO 2021-2022.', 'Desde el ANPA en colaboración con el Ayuntamiento de Valle del Dubra estamos intentando ofertar el Servicio de Madrugadores, para eso necesitamos saber el número de niños/as que estuvieran interesados/as. Se necesita un número mínimo para que sea viable. Enviaremos un modelo de solicitud para cubrir los que esteáis interesados/as, y devolver cubierto al Buzón del ANPA antes del 11 de Junio.', 'Imágenes/Blog/ServicioDeMadrugadores.png', '2021-05-31 20:38:00'),
	(14, 'CONCILIA VERANO', 'Plazo de inscripción hasta el 21 de Junio. Precio: 4€/día.', 'Imágenes/Blog/ConciliaVerán.jpg', '2021-06-11 11:06:00'),
	(15, 'ASAMBLEA GENERAL ', 'Viernes 18 de Junio a las 21:00 horas en el gimnasio de secundaria del CPI de Bembibre. Orden del día: <br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Lectura y aprobación del Acta de la &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Asamblea anterior.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Estado de cuentas.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. Servicio de madrugadores.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4. Actividades extraescolares curso &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2021-2022 (grupos burbuja).<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5. Tareas realizadas por el ANPA en el &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;curso 2021-2022 (relatorios online, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;reclamaciones del arreglo del colegio, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;etc..).<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6. Ruegos y preguntas.', 'Imágenes/Blog/Asamblea.jpg', '2021-06-11 11:11:00'),
	(16, 'MENÚ ESCOLAR JUNIO 2021', 'Estimadas familias,<br/><br/>Ya está puesto el menú del comedor para el mes de Junio.<br/><br/>Saludos cordiales.<br/><br/>El CPI de Bembibre.<br/><br/>URL: <a href="https://tokapp.com/url/8o2dy3io">https://tokapp.com/url/8o2dy3io</a>', 'Imágenes/Blog/MenúXuño2021.png', '2021-06-11 13:30:00'),
	(17, 'PATINAJE', 'Cómo bien sabéis, debido al protocolo COVID de la Consejería de Educación el ANPA no puede ofertar las actividades extraescolares (existencia de grupos burbuja en los centros educativos). Las actividades pueden hacerse siempre que sea a través de clubs federados. En el caso de patinaje se podría llevar a cabo, actividad que sería a cargo del Club Galia. Para esto los/as niños/as tendrían que federarse ya que es la única forma de poder hacer la actividad. La ficha federativa cuesta 20 euros y el precio de la clase depende del número de niños/as que se anoten. Sería Los sábados por la mañana y la profesora sería siendo Sheila. Para que el Club pueda montar los grupos necesitan saber quien quiere anotarse, para poder decirlo y que se pongan en contacto con ustedes. Enviad e-mail a <a href="mailto:bembibre.anpa@gmail.com">bembibre.anpa@gmail.com</a>.', 'Imágenes/Blog/Patinaxe.png', '2021-09-19 16:05:00'),
	(18, 'ASAMBLEA XERAL ', 'Viernes 24 de Septiembre a las 21:00 horas en el gimnasio de secundaria del CPI de Bembibre. Orden del día: <br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Lectura del Acta de la Asamblea &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;anterior.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Estado de cuentas de la Asociación.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. Cuota del ANPA y seguro escolar.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4. Hoja de inscripción de la ANPA y &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;normativa de la protección de datos.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5. Actividades extraescolares y &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;protocolo COVID-19.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6. Ruegos e preguntas.', 'Imágenes/Blog/Asamblea.jpg', '2021-09-19 16:13:00'),
	(19, 'TALLERES DE TEATRO', 'Clases de Teatro en Santa Comba para todos/as, grupos para todas las edades.', 'Imágenes/Blog/TeatroMaiores.png', '2021-09-19 16:18:00'),
	(20, 'TALLERES DE TEATRO', 'Clases de Teatro en Santa Comba para niños/as.', 'Imágenes/Blog/TeatroNenos.png', '2021-09-19 16:23:00'),
	(21, 'PORNOGRAFÍA Y CAMBIOS EN LAS RELACIONES INTERPERSONALES', 'CHARLAS PADRES E MADRES: "Pornografía y cambios en las relaciones interpersonales". Lunes 15 de Noviembre y lunes 22 de Noviembre desde las 18:00 hasta las 19:30 horas en el Auditorio del Ayuntamiento de Bembibre. Internet es hoy la fuente principal de educación sexual de la juventud: el acceso a la pornografía machista y vejatoria se generaliza a partir de los 14 años. ¿CÓMO DEBEMOS EDUCAR PARA FOMENTAR RELACIONES SEXUALES Y AFECTIVAS LIBRES, IGUALITARIAS Y RESPETUOSAS CON LA DIVERSIDAD?', 'Imágenes/Blog/PornografíaECambiosNasRelaciónsInterpersoais.png', '2021-11-11 21:25:00'),
	(22, 'CRECIENDO CON INTERNET Y LAS REDES SOCIALES: CLAVES PARA COMPENDER E PREVENIR', 'IMPORTANTE: Martes 25 de Enero a las 19.30 horas en el Auditorio de Bembibre, charla: "Crecienndo con Internet y las redes sociais: claves para comprender e prevenir". Impartida por la psicóloga Patricia Gómez Salgado (Investigadora de la USC. Experta en adolescentes y TICs). Esta charla se realiza con la ayuda del Centro Autonómico de Formación e Innovación (CAFI) de la Consejería de Cultura, Educación y Universidad.', 'Imágenes/Blog/RiscosDoUsoDeInternetEAsRedesSociais.png', '2022-01-20 22:32:00'),
	(23, 'AYUDAS PARA LIBROS Y MATERIAL ESCOLAR', 'La Xunta abre el plazo para que las familias soliciten yxudas para libros y material escolar y acceso al fondo solidario de manuais.<br/><br/>Más información en la páxina web: <a href="https://www.xunta.gal/notas-de-prensa/-/nova/69002/xunta-abre-prazo-para-que-familias-soliciten-axudas-para-libros-material-escolar">https://www.xunta.gal/notas-de-prensa/-/nova/69002/xunta-abre-prazo-para-que-familias-soliciten-axudas-para-libros-material-escolar</a>.', 'Imágenes/Blog/LibrosEMaterialEscolar.png', '2022-05-23 17:25:00'),
	(24, 'COMIENZO DEL CURSO ESCOLAR 2022/2023', 'El próximo jueves día 8 comienza el curso escolar 2022-23 y desde el ANPA CPI Bembibre deseamos un muy buen curso para niños/as, profes, profesores/as, nais/pais y todo el personal del CPI Bembibre.<br/><br/>Páina web del calendario escolar: <a href="https://www.eldiario.es/galicia/calendario-escolar-curso-2022-23-galicia-inicio-clases-vacaciones-dias-no-lectivos_1_9046076.html">https://www.eldiario.es/galicia/calendario-escolar-curso-2022-23-galicia-inicio-clases-vacaciones-dias-no-lectivos_1_9046076.html</a>', 'Imágenes/Blog/CalendarioEscolar22-23.png', '2022-09-04 19:32:00'),
	(25, 'MENÚ ESCOLAR SEPTIEMBRE 2022', 'Menú del comedor escolar para el mes de Septiembre.', 'Imágenes/Blog/MenúSetembro2022.png', '2022-09-10 12:53:00'),
	(26, 'BONO CUIDADO, UNA AYUDA PARA LA CONCILIACIÓN FAMILIAR', 'Más información:<br/><br/><a href="https://politicasocial.xunta.gal/es/recursos/ayudas/bono-coidado-una-ayuda-para-la-conciliacion-de-las-familias">https://politicasocial.xunta.gal/es/recursos/ayudas/bono-coidado-una-ayuda-para-la-conciliacion-de-las-familias</a>', 'Imágenes/Blog/BonoCoidadoXunta.png', '2022-09-10 13:01:00'),
	(27, 'I EDICIÓN SANTIAGO DE COMPOSTELA EN MARCHA CONTRA EL CÁNCER', 'Caminata solidaria (5km) y Feria divulgativa "Ciencia para todos".<br/><br/>Más información:<br/<br/><a href="https://enmarchacontraelcancer.es/es/evento/santiago-de-compostela-en-marcha-contra-o-cancro">https://enmarchacontraelcancer.es/es/evento/santiago-de-compostela-en-marcha-contra-o-cancro</a>.', 'Imágenes/Blog/IEdiciónMarchaContraOCancro.jpg', '2022-09-16 22:20:00'),
	(28, 'AVISO IMPORTANTE', 'Este viernes 30 de septiembre acaba el plazo para hacerse socio/a del ANPA. Recordad enviar solicitud de inscripción y hacer el ingreso. Cuota: 15€ por familia.', 'Imágenes/logo.png', '2022-09-29 19:50:00'),
	(29, 'CURSOS DE FORMACIÓN PARA MUJERES', 'Cursos gratuitos de formación en competencias digitales para mujeres desempleadas o en demanda de la mejora de empleo. A finales de curso llevan una TABLET de Regalo. Más información en <a href="https://www.mullerdixital.gal/">www.mullerdixital.gal</a>.', 'Imágenes/Blog/MullerDixital.png', '2022-12-19 20:54:00'),
	(30, 'CAMPAÑA SOLIDARIA DE RECOGIDA DE ALIMENTOS', 'Desde Cáritas Val do Dubra nos piden la colaboración en la recogida de alimentos no percederos. En el Colegio CPI de Bembibre va haber un espacio habilitado en el hall de la entrada para depositar alimentos no percederos y aquellas familias que quieran colaborar pueden allegar los alimentos a través de sus hijos/as. Desde el ANPA CPI Bembibre solicitamos la colaboración de todos/as en esta campaña solidaria.', 'Imágenes/Blog/Cáritas.png', '2022-12-19 21:00:00'),
	(31, 'COLABORADORAS/ES PARA EL COMEDOR ESCOLAR DEL CPI BEMBIBRE', 'URGENTE: Se necesitan colaboradoras/es para el comedor escolar del CPI Bembibre (Val do Dubra - A Coruña). El número de colaboradoras/es va en función del número de niños/as que comen en el comedor escolar, si hay menos colaboradoras/es habrá menos niños/as en el comedor escolar. Para evitar esto necesitamos colaboradores/as para el comedor escolar del CPI Bembibre. Pueden ser colaboradoras/es del comedor escolar: padres y madres, familiares de alumnos/as (tios, abuelos, y hermanos mayores de edad), ex-colaboradores de este servicio, personas que participen en programas de voluntariado social en ayuntamientos o en ONGS. Los colaboradores/as pueden comer de forma gratuita en el centro los días que colaboren y perciban 12,50 euros por asistencia. El horario es desde las 14:15 horas (pueden comer antes) hasta las 16:15 horas. Si hay personas interesadas que se pongan en contacto con el centro lo antes posible.', 'Imágenes/Blog/ColexioDeBembibre.jpg', '2023-03-29 12:14:58'),
	(32, 'CAMPAMENTOS DE VERANO 2023', 'Ábrese el plazo hasta el 2 de Mayo para solicitar plaza para los campamentos que oferta la Xunta de Galicia para niños de 9 a 17 años. Las solicitudes se tramitarán a través de la sede electrónica de la Xunta.', 'Imágenes/Blog/Campamentos2023.jpg', '2023-04-20 19:18:37'),
	(33, 'TEATRO PARA TODOS/AS', 'Este sábado 29 de Abril a las 18:00 da tarde Teatro para niños/as y padres y madres en el Auditorio de Bembibre (Valle del Dubra).', 'Imágenes/Blog/TeatroAsPalabrasPerdidas.jpg', '2023-04-26 11:29:43'),
	(34, 'ASAMBLEA GENERAL', 'Orden del día de la Asamblea General de Socios/as el 9 de Junio en el Gimnasio Secundaria del CPI Bembibre a las 21.30 horas:<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Lectura y aprobación da acta da Asamblea Anterior.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Estado de contas.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. Dimisión de algunos/as integrantes de la Directiva y nuevas incorporaciones a la Directiva.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4. Votación para decidir si se hace o no la Fiesta de Fin de Curso.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5. Votación para decidir si se hace la aportación del ANPA a la Excursión de Fin de Curso, y en el caso de hacerla si se hace para los socios/as del ANPA o para todo/as (socios/as o no socios/as)<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6. Ruegos e preguntas', 'Imágenes/Blog/ColexioDeBembibre.jpg', '2023-05-30 22:27:19'),
	(35, 'FIESTA ANPA FIN DE CURSO', 'El próximo domingo 25 de Junio tendrá lugar la Fiesta de Fin de Curso en el patio del CPI Bembibre, a partir de las 16.30 horas.\r\nHabrá hinchables y Fiesta de la Espuma y meriendas para todos/as\r\nEnviar un correo al e-mail de la ANPA (bembibre.anpa@gmail.com) diciendo cuantos niños/as y adultos/as vienen a la Fiesta ANTES del martes 20 de Junio.\r\nTodos los niños/as tienen que estar acompañados por un adulto/a.\r\nImportante: notificar en el correo si hay algún niño/a con intolerancia alimentaria y de que tipo.\r\nLa Fiesta es GRATIS para los socios/as.\r\nLos no socios/as pueden asistir pagando 15 euros por familia.', 'Imágenes/Blog/ColexioDeBembibre.jpg', '2023-06-14 11:28:38'),
	(36, 'FIESTA ANPA CPI BEMBIBRE', 'Fiesta del ANPA del CPI Bembibre del 25 de Junio.', 'Imágenes/Blog/FestaANPACpiBembibre.jpg', '2023-09-25 11:23:41'),
	(37, 'ASAMBLEA GENERAL', 'ASAMBLEA GENERAL SOCIOS/AS Viernes 15 de Septiembre a las 21 horas en el Gimnasio de Secundaria CPI Bembibre. Orden del día de la Asamblea: \r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1. Lectura y aprobación del Acta de la Asamblea Anterior.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2. Estado de cuentas de la Asociación.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3. Dimisión de la Junta Directiva y elección de la nueva Junta Directiva.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4. Actividades Extraescolares.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;5. Uniforme escolar alumnado CPI Bembibre.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6. Ruegos y Preguntas.', 'Imágenes/Blog/ColexioDeBembibre.jpg', '2023-09-09 11:58:33'),
	(38, 'ACTIVIDADES EXTRAESCOLARES Y CUOTA DEL SOCIO/A ', 'CURSO 2023/2024 \r\nACTIVIDADES EXTRAESCOLARES ANPA CPI BEMBIBRE Y CUOTA DE SOCIO/A.\r\nEl próximo día 27 de Septiembre es el último día para anotarse en las actividades extraescolares del ANPA. \r\nEste año ofrecemos:\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Pintura: 22 euros/mes.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Danza: 21 euros/mes.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Mecanografia: 22 euros/mes.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Robótica: 22 euros/mes.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Inglés: 22 euros/mes.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Teatro: 27 euros /mes.\r\n<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Multideporte: 24 euros/mes.<br/><br/>\r\nComo dijimos en la Asamblea este curso sólo tenemos un aula para las clases de inglés y pintura con lo cual los grupos de niños/as van a ser distintos al año pasado, para poder tener estas dos actividades extraescolares.\r\nLos primeros 15 días de Octubre habá jornadas de Puertas Abiertas, para que los niños/as vean si les gusta la actividad.\r\nUna vez anotado definitivamente un niño/a no podrá dejar la actividad, excepto causa de fuerza mayor.\r\nPara poder ir a las actividades hay que ser socio/a de la ANPA.\r\nLa cuota de socio es por curso, son 15 euros *por familia*.\r\nHay que ingresar los 15 euros en la cuenta bancaria del ANPA antes del 31 de Octubre.\r\nEl seguro escolar del ANPA son 10 euros *por niño/a* por curso.\r\nRecordamos que este seguro es voluntario.\r\nCorreo electrónico ANPA CPI Bembibre: <a href="mailto:bembibre.anpa@gmail.com">bembibre.anpa@gmail.com</a>', 'Imágenes/Blog/ColexioDeBembibre.jpg', '2023-09-18 21:07:23'),
	(39, 'ACTIVIDAD EXTRAESCOLAR DE TEATRO', 'ACTIVIDAD EXTRAESCOLAR ANPA CPI BEMBIBRE. A partir de siete años de edad.', 'Imágenes/Blog/TeatroActividadeExtraescolarCurso2324.jpg', '2023-10-04 16:23:28'),
	(40, 'TEATRO FAMILIAR', 'TEATRO FAMILIAR este sábado 18 de Novembro a las 20 horas en el Auditorio Municipal en Bembibre (Valle del Dubra).', 'Imágenes/Blog/TeatroFamiliar.jpg', '2023-11-16 19:39:20'),
	(41, 'CAMPAMENTO DE NAVIDAD EN VALLE DEL DUBRA', 'Campamento de navidad en el Valle Del Dubra.', 'Imágenes/Blog/CampamentoNadal.jpg', '2023-11-23 17:01:56'),
	(42, 'CAMPAMENTO DE NAVIDAD DE MULTIDEPORTE', 'CAMPAMENTO DE NAVIDAD DE MULTIDEPORTE DEL ANPA DE BEMBIBRE\r\nDesde hoy y hasta el 3 de Diciembre se encuentra abierta la inscripción del Campamento de Navidad del ANPA del CPI de Bembibre\r\nSemana 1: Del 26 al 29 de Diciembre.\r\nSemana 2: Del 2 al 5 de Enero.\r\nHorario: 09:00-14:00\r\n(Posibilidad de elegir semanas sueltas). \r\n65€ a la semana\r\n15€ día suelto\r\n95€ campus completo\r\nSe hará un descuento de 15€ a los niños/as que ya están asistiendo a multideporte (del ANPA).\r\nSe necesita un mínimo de 10 asistentes.\r\nINFÓRMATE LLAMANDO AL 616 25 40 95.\r\n<br/>\r\nEnlace: <a href="https://docs.google.com/forms/d/e/1FAIpQLScmnX8euSrYJ9CVnhLxjrgdLzYJieBcySxnT5CmNd1TpYBLOw/viewform">Formulario KFSport</a>', 'Imágenes/Blog/KFSport.png', '2023-11-23 17:04:49'),
	(43, 'CAMPAMENTO ANPA MULTIDEPORTE NAVIDAD 2023', 'CAMPAMENTO ANPA MULTIDEPORTE NAVIDAD 2023.', 'Imágenes/Blog/CampusDeportivo.jpg', '2023-11-23 17:07:45'),
	(45, 'CAMPAMENTO DE CARNAVAL VALLE DEL DUBRA', 'Inscrición gratuita.', 'Imágenes/Blog/CampamentoDeEntroido.jpg', '2023-12-08 18:47:04'),
	(46, '1º PREMIO DEL CLUB DEBATE ALINGUA', 'ENHORABUENA A LOS TESTUDOS (CPI de Bembibre). Muchas felicidades y mucha suerte en la Final.', 'Imágenes/Blog/PremioClubDebateAlingua.jpg', '2024-01-20 17:09:24'),
	(47, 'TESTUDOS DE BEMBIBRE', 'ENHORABUENA A LOS AOS TESTUDOS DE BEMBIBRE (CPI de Bembibre). Los chicos y chicas de Valle del Dubra consiguen su plaza para la final del @clubdedebate_alingua \r\nLos 𝐓𝐞𝐬𝐭𝐮𝐝𝐨𝐬 𝐝𝐞 𝐁𝐞𝐦𝐛𝐢𝐛𝐫𝐞, representando al Ayuntamiento de Valle del Dubra, ganan el primer premio de 800 euros y pasan a la final.\r\nA final da actividade terá lugar el 13 de Abril y acogida por el Ayuntamiento de Valle Del Dubra', 'Imágenes/Blog/TestudosDeBembibre.jpg', '2024-03-01 19:54:33'),
	(48, 'RELATORIO "CUIDANDO LA SALUD MENTAL DE NUESTROS HIJOS/AS"', 'RELATORIO "CUIDANDO LA SALUD MENTAL DE NUESTROS HIJOS/AS" LUNES 22 de Abril a las 20 horas en la Casa de la Cultura de Bembibre. Impartido por la psicóloga Belén Montesa Lou. Nos hablará de la importancia de la autoestima y la regulación de las emociones y como identificar las señales de alerta de posibles problemas emocionales. También se abordarán métodos efectivos para \r\npromover un ambente familiar positivo y de apoyo que contribuya el bienestar emocional y mental de los niños/as. Relatorio financiado por el CAFI, Consejería de Educación.', 'Imágenes/Blog/RelatorioCoidandoASaúdeMentalDosNososFillos.jpg', '2024-03-01 20:18:12'),
	(49, 'TORNEO ESCOLAR AJEDREZ XOGADE', 'TORNEO ESCOLAR AJEDREZ XOGADE. Este jueves 28 de Marzo en la Casa da Cultura de Bembibre, de 12.30 a 14 horas.<br/><br/>Edad: hasta Segundo de la ESO.', 'Imágenes/Blog/TorneoEscolarXadrezXogade.jpg', '2024-03-26 17:04:38'),
	(50, 'CÓMO PREVENIR EL CONSUMO DE SUSTANCIAS ADICTIVAS DESDE LA FAMILIA', 'LUNES 8 ABRIL a las 20 horas, Casa de la Cultura de Bembibre, " CÓMO PREVENIR EL CONSUMO DE SUSTANCIAS ADICTIVAS DESDE LA FAMILIA". Hablará Miriam Otero, Dra. en Psicología. Relatorio financiado por el CAFI, Consejería de Educación.', 'Imágenes/Blog/ComoPrevirOConsumoDeSustanciaAditivasDendeAFamilia.jpg', '2024-04-03 17:30:24'),
	(51, 'DÍA DEL LIBRO. PACO NOGUEIRAS CUENTOS A CIENTOS', 'ESTE VIERNES A LAS 19 HORAS EN LA BIBLIOTECA DE LA CASA DE LA CULTURA', 'Imágenes/Blog/PacoNogueirasContosACentos.jpg', '2024-04-03 17:36:29'),
	(52, 'FINAL CLUB DEBATE ALINGUA', 'HOY "Los Testudos del CPI Bembibre" disputan la Final del Club Debate A Lingua a partir de las 10.30 en el Auditorio de Valle del Dubra. Desde la ANPA les deseamos suerte y expresamos nuestra admiración por su gran trabajo.', 'Imágenes/Blog/ClubDebateALingua.jpg', '2024-04-13 09:04:20'),
	(53, 'FESTIVAL ACTIVIDADES EXTRAESCOLARES', 'SÁBADO 4 DE MAYO: FESTIVAL ACTIVIDADES EXTRAESCOLARES.', 'Imágenes/Blog/FestivalActividadesExtraescolares.jpg', '2024-04-18 18:02:36'),
	(54, 'DETALLES FESTIVAL ACTIVIDADES EXTRAESCOLARES', 'Sábado 4  de mayo FESTIVAL ACTIVIDADES EXTRAESCOLARES ANPA CPI BEMBIBRE. La ANPA traerá pizza y bebida para los niños/as.', 'Imágenes/Blog/FestivalANPABembibre.jpg', '2024-05-01 11:07:22'),
	(55, 'FINAL DE LA OLIMPIADA GALLEGA DE MATEMÁTICAS', 'EL CPI BEMBIBRE PASA A LA FASE FINAL DE LA OLIMPIADA GALLEGA DE MATEMÁTICAS. La fase final se disputará en Lugo el 23 de Mayo. Muchas felicidades a Nicolás Amado, representante del CPI Bembibre en la Olimpiada Matemática. Nicolás es Subcampión Gallego de Ajedrez Sub-14, jugador del Club Ajedrez Valle del Dubra. Ajedrez y matemáticas un binomio perfecto. Más info en <a href="https://agapema.org/.../centros-inscritos-para-a.../">https://agapema.org/.../centros-inscritos-para-a.../</a>', 'Imágenes/Blog/FinalDaOlimpiadaGalegaDeMatemáticas.jpg', '2024-05-09 16:11:30'),
	(56, 'ASAMBLEA GENERAL', 'ASAMBLEA GENERAL SOCIOS/AS VIERNES 7 JUNIO A LAS 21.30 HORAS en la Biblioteca de Secundaria.\r\nOrden del día:<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n1. Lectura del acta de la Asamblea anterior.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n2. Estado de cuentas de la asociación.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n3. Dimisión y elección de integrantes de la Directiva.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n4. Excursión ANPA 30 de Junio.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n5. Actividades extraescolares.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n6. Ruegos y preguntas.', 'Imágenes/Blog/ColexioDeBembibre.jpg', '2024-05-30 12:08:04'),
	(57, 'JORNADA ACTIVIDAD EXTRAESCOLAR MULTIDEPORTE EN SANTA COMBA', 'Viernes 14 Junio Xornada Actividad Extraescolar Multideporte en Santa Comba.\r\nAnimaros a participar. INSCRIPCIÓN antes del miércoles 5 de Junio. Enviar nombre y apellidos do niño/a y fecha de nacimiento a Kevin (616254095).', 'Imágenes/Blog/XornadaMultideporteSantaComba.jpg', '2024-05-30 19:21:47'),
	(58, 'EXCURSIÓN ANPA ECO-PARQUE ATALAYA ', 'Domingo 30 de Junio. Salida a las 09:00 horas desde el CPI de Bembibre. La excursión incluye las actividades en el Eco-parque, la comida completa del medio-día y el viaje en autobús. Los niños/as de los socios/as del ANPA no pagan nada. Prezo adulto socio/a 37 euros. Los niños/as NO socios/as precio 30 euros y el adulto no socio 47 euros. Importante: úlimo día para anotarse el 13 de Junio.', 'Imágenes/Blog/ExcursiónEcoParqueAtalaia.jpg', '2024-05-31 20:45:15'),
	(59, 'PLAZAS AGOTADAS PARA LA EXCURSIÓN AL ECO-PARQUE ATALAYA', 'EXCURSIÓN ANPA 30 DE XUÑO ECO-PARQUE ATALAYA. Después de acabar el prazo de inscripción, y debido a que ya no hay plazas, NO se anota a más participantes. Feliciadades a todos/as por el éxito de la convocatoria.', 'Imágenes/Blog/EcoParqueAtalaia.jpg', '2024-06-15 18:33:16'),
	(60, 'ECO-PARQUE ATALAYA (COTOBADE)', 'EXCURSION ANPA CPI BEMBIBRE ECO-PARQUE ATALAYA (Cotobade)', 'Imágenes/Blog/ExcursionistascoParqueAtalaia.jpg', '2024-07-01 12:47:12'),
	(61, 'CAMPAMENTO DIGITAL EN VALLE DEL DUBRA', 'Abierta la preinscripción para el #CampamentoDixital en Valle del Dubra.<br/><br/>\r\nSi tienes entre 9 e 17 años, ¡participa en este campamento gratuíto de 30 horas para aprender competencias digitales!<br/><br/>\r\nDel 7 de Octubre al 29 de Noviembre, en las tardes de los lunes y jueves en la Biblioteca Municipal de Valle del Dubra.<br/><br/>\r\nDos grupos disponibles:<br/><br/>\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- 9 a 13 años: 17:00 - 19:00 h.\r\n&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- 14 a 17 años: 19:00 - 21:00 h.<br/><br/>\r\nAprende sobre seguridad en la red, uso responsable de las redes sociales y mucho más, todo mientras te diviertes en aventuras digitales adaptadas a tu edad.<br/><br/>\r\nInscripción abierta hasta el 25 de Septiembre en el Registro General del Ayuntamiento o a través de la sede electrónica.<br/><br/>\r\n¡No pierdas la oportunidad!', 'Imágenes/Blog/CampamentoDixital.jpg', '2024-09-12 17:58:47'),
	(62, 'ASAMBLEA GENERAL', 'CONVOCATORIA ASAMBLEA XERAL SOCIOS/AS ANPA CPI BEMBIBRE:<br/><br/>\r\nViernes 13 de Septiembre a las 21.30 horas en la Biblioteca de Secundaria del CPI Bembibre.<br/><br/>\r\nOrden del día:<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n1. Lectura y aprobación del acta de la Asamblea General Anterior.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n2. Estado de cuentas de la Asociación.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n3. Renovación de integrantes de la directiva ANPA.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n4. Actividades extraescolares curso 2024/2025.<br/><br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n5. Ruegos y preguntas.', 'Imágenes/Blog/ColexioDeBembibre.jpg', '2024-09-25 21:52:20');

-- Volcando estructura para tabla anpacpivaldodubraes.comentarios
DROP TABLE IF EXISTS `comentarios`;
CREATE TABLE IF NOT EXISTS `comentarios` (
  `Id_Comentario` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `Nombre` varchar(100) NOT NULL,
  `Correo` varchar(100) NOT NULL,
  `Comentario` longtext NOT NULL,
  `Fecha_Publicación` datetime NOT NULL,
  PRIMARY KEY (`Id_Comentario`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcando datos para la tabla anpacpivaldodubraes.comentarios: ~1 rows (aproximadamente)
REPLACE INTO `comentarios` (`Id_Comentario`, `Nombre`, `Correo`, `Comentario`, `Fecha_Publicación`) VALUES
	(1, 'Blasco Rodríguez Porta', 'blascorodriguez@gmail.com', 'Comentario de prueba desde la página de contacto.', '2024-09-21 22:42:15');

-- Volcando estructura para tabla anpacpivaldodubraes.usuarios
DROP TABLE IF EXISTS `usuarios`;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `Id_Usuario` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `Usuario` varchar(50) NOT NULL,
  `Contraseña` varchar(50) NOT NULL,
  `Nombre` varchar(100) NOT NULL,
  `Correo` varchar(100) NOT NULL,
  `Teléfono` varchar(20) DEFAULT NULL,
  `Encuentro` enum('Motor de búsqueda','Medios sociales','TV','Radio','Amigo o familiar') DEFAULT NULL,
  `OtrosDetalles` longtext DEFAULT NULL,
  `MeGustaIndex` enum('Sí','No') NOT NULL,
  `MeGustaSobreNosotros` enum('Sí','No') NOT NULL,
  `MeGustaEstatutos` enum('Sí','No') NOT NULL,
  `MeGustaContacto` enum('Sí','No') NOT NULL,
  PRIMARY KEY (`Id_Usuario`),
  UNIQUE KEY `Usuario` (`Usuario`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Volcando datos para la tabla anpacpivaldodubraes.usuarios: ~2 rows (aproximadamente)
REPLACE INTO `usuarios` (`Id_Usuario`, `Usuario`, `Contraseña`, `Nombre`, `Correo`, `Teléfono`, `Encuentro`, `OtrosDetalles`, `MeGustaIndex`, `MeGustaSobreNosotros`, `MeGustaEstatutos`, `MeGustaContacto`) VALUES
	(1, 'admin', 'abc123.,', 'Administrador', 'admin@admin.es', '608736780', 'Amigo o familiar', NULL, 'No', 'No', 'No', 'No'),
	(2, 'juaninsua', 'abc123.,', 'Juan José Insua Louro', 'juan.insua.bembibre@edu.xunta.es', '678491234', 'Medios sociales', 'Hola Blasco, soy Juan el compañero de Ruth.', 'No', 'No', 'No', 'No');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
